export const FETCH_CURRENT = 'FETCH_CURRENT';
export const FETCH_CURRENT_SUCCESS = 'FETCH_CURRENT_SUCCESS';
export const FETCH_CURRENT_FAILURE = 'FETCH_CURRENT_FAILURE';

export const FETCH_WEEKLY = 'FETCH_WEEKLY';
export const FETCH_WEEKLY_SUCCESS = 'FETCH_WEEKLY_SUCCESS';
export const FETCH_WEEKLY_FAILURE = 'FETCH_WEEKLY_FAILURE';
